/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	appsv1 "krome/pkg/apis/apps/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStatefulsets implements StatefulsetInterface
type FakeStatefulsets struct {
	Fake *FakeAppsV1
	ns   string
}

var statefulsetsResource = schema.GroupVersionResource{Group: "apps.krome.io", Version: "v1", Resource: "statefulsets"}

var statefulsetsKind = schema.GroupVersionKind{Group: "apps.krome.io", Version: "v1", Kind: "Statefulset"}

// Get takes name of the statefulset, and returns the corresponding statefulset object, and an error if there is any.
func (c *FakeStatefulsets) Get(ctx context.Context, name string, options v1.GetOptions) (result *appsv1.Statefulset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(statefulsetsResource, c.ns, name), &appsv1.Statefulset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Statefulset), err
}

// List takes label and field selectors, and returns the list of Statefulsets that match those selectors.
func (c *FakeStatefulsets) List(ctx context.Context, opts v1.ListOptions) (result *appsv1.StatefulsetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(statefulsetsResource, statefulsetsKind, c.ns, opts), &appsv1.StatefulsetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appsv1.StatefulsetList{ListMeta: obj.(*appsv1.StatefulsetList).ListMeta}
	for _, item := range obj.(*appsv1.StatefulsetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested statefulsets.
func (c *FakeStatefulsets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(statefulsetsResource, c.ns, opts))

}

// Create takes the representation of a statefulset and creates it.  Returns the server's representation of the statefulset, and an error, if there is any.
func (c *FakeStatefulsets) Create(ctx context.Context, statefulset *appsv1.Statefulset, opts v1.CreateOptions) (result *appsv1.Statefulset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(statefulsetsResource, c.ns, statefulset), &appsv1.Statefulset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Statefulset), err
}

// Update takes the representation of a statefulset and updates it. Returns the server's representation of the statefulset, and an error, if there is any.
func (c *FakeStatefulsets) Update(ctx context.Context, statefulset *appsv1.Statefulset, opts v1.UpdateOptions) (result *appsv1.Statefulset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(statefulsetsResource, c.ns, statefulset), &appsv1.Statefulset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Statefulset), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStatefulsets) UpdateStatus(ctx context.Context, statefulset *appsv1.Statefulset, opts v1.UpdateOptions) (*appsv1.Statefulset, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(statefulsetsResource, "status", c.ns, statefulset), &appsv1.Statefulset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Statefulset), err
}

// Delete takes name of the statefulset and deletes it. Returns an error if one occurs.
func (c *FakeStatefulsets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(statefulsetsResource, c.ns, name), &appsv1.Statefulset{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStatefulsets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(statefulsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &appsv1.StatefulsetList{})
	return err
}

// Patch applies the patch and returns the patched statefulset.
func (c *FakeStatefulsets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appsv1.Statefulset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(statefulsetsResource, c.ns, name, pt, data, subresources...), &appsv1.Statefulset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appsv1.Statefulset), err
}
