apiVersion: apps.krome.io/v1
kind: Deployment
metadata:
  name: deploy-example
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy-example
  template:
    metadata:
      labels:
        app: deploy-example
    spec:
      containers:
      - name: deploy-example
        image: nginx:1.12.2
        imagePullPolicy: IfNotPresent
        env:
        - name: env-test-1
          value: env-value-1
#        volumeMounts:
#        - mountPath: /mnt
#          name: mnt
      readinessGates:
      - conditionType: InPlaceUpdateReady
  podManagementPolicy: Parallel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      maxSurge: 1
      maxUnavailable: 0
      #partition: 0
#  volumeClaimTemplates:
#  - metadata:
#      name: mnt
#      annotations:
#        volume.beta.kubernetes.io/storage-class: csi-hostpath-sc
#    spec:
#      accessModes:
#      - ReadWriteOnce
#      resources:
#        requests:
#          storage: 200Mi
