apiVersion: apps.krome.io/v1
kind: StatefulSet
metadata:
  name: statefulset-example
spec:
  replicas: 4
  selector:
    matchLabels:
      app: statefulset-example
  template:
    metadata:
      labels:
        app: statefulset-example
    spec:
      containers:
      - name: statefulset-example
        image: nginx:1.12.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mnt
          name: mnt
      ReadinessGates:
      - conditionType: InPlaceUpdateReady
  PodManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      #maxUnavailable: 1
      #partition: 0
  volumeClaimTemplates:
  - metadata:
      name: mnt
      annotations:
        volume.beta.kubernetes.io/storage-class: csi-hostpath-sc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200Mi
