/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/zhonglin6666/krome/pkg/apis/apps/v1"
	scheme "github.com/zhonglin6666/krome/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StatefulsetsGetter has a method to return a StatefulsetInterface.
// A group's client should implement this interface.
type StatefulsetsGetter interface {
	Statefulsets(namespace string) StatefulsetInterface
}

// StatefulsetInterface has methods to work with Statefulset resources.
type StatefulsetInterface interface {
	Create(ctx context.Context, statefulset *v1.Statefulset, opts metav1.CreateOptions) (*v1.Statefulset, error)
	Update(ctx context.Context, statefulset *v1.Statefulset, opts metav1.UpdateOptions) (*v1.Statefulset, error)
	UpdateStatus(ctx context.Context, statefulset *v1.Statefulset, opts metav1.UpdateOptions) (*v1.Statefulset, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Statefulset, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.StatefulsetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Statefulset, err error)
	StatefulsetExpansion
}

// statefulsets implements StatefulsetInterface
type statefulsets struct {
	client rest.Interface
	ns     string
}

// newStatefulsets returns a Statefulsets
func newStatefulsets(c *AppsV1Client, namespace string) *statefulsets {
	return &statefulsets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the statefulset, and returns the corresponding statefulset object, and an error if there is any.
func (c *statefulsets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Statefulset, err error) {
	result = &v1.Statefulset{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("statefulsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Statefulsets that match those selectors.
func (c *statefulsets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.StatefulsetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.StatefulsetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("statefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested statefulsets.
func (c *statefulsets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("statefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a statefulset and creates it.  Returns the server's representation of the statefulset, and an error, if there is any.
func (c *statefulsets) Create(ctx context.Context, statefulset *v1.Statefulset, opts metav1.CreateOptions) (result *v1.Statefulset, err error) {
	result = &v1.Statefulset{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("statefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(statefulset).
		Do().
		Into(result)
	return
}

// Update takes the representation of a statefulset and updates it. Returns the server's representation of the statefulset, and an error, if there is any.
func (c *statefulsets) Update(ctx context.Context, statefulset *v1.Statefulset, opts metav1.UpdateOptions) (result *v1.Statefulset, err error) {
	result = &v1.Statefulset{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("statefulsets").
		Name(statefulset.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(statefulset).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *statefulsets) UpdateStatus(ctx context.Context, statefulset *v1.Statefulset, opts metav1.UpdateOptions) (result *v1.Statefulset, err error) {
	result = &v1.Statefulset{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("statefulsets").
		Name(statefulset.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(statefulset).
		Do().
		Into(result)
	return
}

// Delete takes name of the statefulset and deletes it. Returns an error if one occurs.
func (c *statefulsets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("statefulsets").
		Name(name).
		Body(&opts).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *statefulsets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("statefulsets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do().
		Error()
}

// Patch applies the patch and returns the patched statefulset.
func (c *statefulsets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Statefulset, err error) {
	result = &v1.Statefulset{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("statefulsets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do().
		Into(result)
	return
}
