apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: StatefulSets.apps.krome.io
spec:
  group: apps.krome.io
  names:
    kind: StatefulSet
    listKind: StatefulSetList
    plural: StatefulSets
    singular: StatefulSet
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: StatefulSet is the Schema for the StatefulSets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: StatefulSetSpec defines the desired state of StatefulSet
          type: object
        status:
          description: StatefulSetStatus defines the observed state of StatefulSet
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
