apiVersion: apps/v1
kind: Deployment
metadata:
  name: krome
spec:
  replicas: 1
  selector:
    matchLabels:
      name: krome
  template:
    metadata:
      labels:
        name: krome
    spec:
      serviceAccountName: krome
      containers:
        - name: krome
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - krome
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "krome"
